CREATE DATABASE IF NOT EXISTS CICD_DEMO;
CREATE SCHEMA IF NOT EXISTS CICD_DEMO.TEST;
CREATE SCHEMA IF NOT EXISTS CICD_DEMO.PROD;

CREATE WAREHOUSE IF NOT EXISTS CICD_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE ROLE IF NOT EXISTS CICD_ROLE;
GRANT USAGE ON DATABASE CICD_DEMO TO ROLE CICD_ROLE;
GRANT USAGE ON SCHEMA CICD_DEMO.TEST TO ROLE CICD_ROLE;
GRANT USAGE ON SCHEMA CICD_DEMO.PROD TO ROLE CICD_ROLE;
GRANT ALL ON SCHEMA CICD_DEMO.TEST TO ROLE CICD_ROLE;
GRANT ALL ON SCHEMA CICD_DEMO.PROD TO ROLE CICD_ROLE;
GRANT USAGE ON WAREHOUSE CICD_WH TO ROLE CICD_ROLE;

CREATE USER IF NOT EXISTS CICD_RUNNER
    DEFAULT_ROLE = CICD_ROLE
    DEFAULT_WAREHOUSE = CICD_WH;
GRANT ROLE CICD_ROLE TO USER CICD_RUNNER;


ALTER USER CICD_RUNNER SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArEcLSz2wjeuOT+dImVV0vWWogihcUa/L2qSkhhOBK683i8rEdIKhbeiNPUzqyLnXTmiD2g8gp9SpdULs22iO+ZgNMiUDfe9HDH/G6W/zm4/QezWkXMzLyP2ffugyI0tg5wDvwvIVHUW6RLcoxMufKm2Cv1zt8ANdX936t0E0vNSP950+Hqji4qIwUTWaeImMROL2+mt4INmE3zdJ9daaVSDa5Gfa3BpUL5pGIT2M91EXe0jp1rmi/DiALrsy52WqMiWgbNfXD7ULUhS6YQ98aYcwGLK7cMzkyc354N6bpaGkoYmJm2SFLChEKRtcRHwYvRg237n7wYbS+TLvlXwshwIDAQAB';




