CREATE OR REPLACE TABLE CICD_DEMO.<% schema %>.OWNER (
    OWNER_ID        INT             NOT NULL,
    OWNER_NAME      VARCHAR(200)    NOT NULL,
    OWNER_CATEGORY  VARCHAR(20)     NOT NULL,  -- INDIVIDUAL, INVESTOR, COMMERCIAL

    CONSTRAINT pk_owner PRIMARY KEY (OWNER_ID)
);
