CREATE OR REPLACE TABLE CICD_DEMO.__SCHEMA__.OWNER (
    OWNER_ID        INT             NOT NULL,
    OWNER_NAME      VARCHAR(200)    NOT NULL,
    OWNER_CATEGORY  VARCHAR(20)     NOT NULL,  -- INDIVIDUAL, INVESTOR, COMMERCIAL

    CONSTRAINT pk_owner PRIMARY KEY (OWNER_ID),
    CONSTRAINT chk_owner_category CHECK (OWNER_CATEGORY IN ('INDIVIDUAL', 'INVESTOR', 'COMMERCIAL'))
);
