CREATE OR REPLACE TABLE CICD_DEMO.<% schema %>.PROPERTY (
    PROPERTY_ID     INT             NOT NULL,
    ADDRESS         VARCHAR(300)    NOT NULL,
    SQUARE_FEET     INT             NOT NULL,
    ZIP_CODE        VARCHAR(10)     NOT NULL,
    OWNER_ID        INT             NOT NULL,

    CONSTRAINT pk_property PRIMARY KEY (PROPERTY_ID),
    CONSTRAINT fk_property_owner FOREIGN KEY (OWNER_ID) REFERENCES CICD_DEMO.<% schema %>.OWNER(OWNER_ID)
);
