CREATE OR REPLACE TABLE CICD_DEMO.__SCHEMA__.PROPERTY_EVENT (
    EVENT_ID        INT             NOT NULL,
    PROPERTY_ID     INT             NOT NULL,
    EVENT_TYPE      VARCHAR(20)     NOT NULL,  -- PURCHASE, ABANDONMENT, CONDEMNATION, APPROVED
    EVENT_DATE      DATE            NOT NULL,

    CONSTRAINT pk_property_event PRIMARY KEY (EVENT_ID),
    CONSTRAINT fk_event_property FOREIGN KEY (PROPERTY_ID) REFERENCES CICD_DEMO.__SCHEMA__.PROPERTY(PROPERTY_ID)
);
