CREATE OR REPLACE DYNAMIC TABLE CICD_DEMO.<% schema %>.PROPERTY_STATUS_BY_ZIP
    TARGET_LAG = '1 minute'
    WAREHOUSE = CICD_WH
AS
WITH latest_event AS (
    SELECT
        pe.PROPERTY_ID,
        pe.EVENT_TYPE,
        ROW_NUMBER() OVER (PARTITION BY pe.PROPERTY_ID ORDER BY pe.EVENT_DATE DESC, pe.EVENT_ID DESC) AS rn
    FROM CICD_DEMO.<% schema %>.PROPERTY_EVENT pe
)
SELECT
    p.ZIP_CODE,
    COUNT_IF(le.EVENT_TYPE = 'PURCHASE')      AS PURCHASE_COUNT,
    COUNT_IF(le.EVENT_TYPE = 'ABANDONMENT')   AS ABANDONMENT_COUNT,
    COUNT_IF(le.EVENT_TYPE = 'CONDEMNATION')  AS CONDEMNATION_COUNT,
    COUNT_IF(le.EVENT_TYPE = 'APPROVED')      AS APPROVED_COUNT,
    COUNT_IF(le.EVENT_TYPE = 'DEMOLISHED')    AS DEMOLISHED_COUNT,
    COUNT_IF(le.EVENT_TYPE = 'MERGED')        AS MERGED_COUNT,
    COUNT(*)                                   AS TOTAL_PROPERTIES
FROM latest_event le
JOIN CICD_DEMO.<% schema %>.PROPERTY p ON p.PROPERTY_ID = le.PROPERTY_ID
WHERE le.rn = 1
GROUP BY p.ZIP_CODE;
